from django.urls import path
from . import views
urlpatterns=[path('',views.index,name='index'),
path('openFile',views.openFile,name='openFile'),
path('getImage',views.getImage,name='getImage'),
path('toGrayscale',views.toGrayscale,name='toGrayscale'),
path('getState',views.getState,name='getState'),
path('closeFile',views.closeFile,name='closeFile'),
path('getDimension',views.getDimension,name='getDimension'),
path('getBorder',views.getBorder,name='getBorder'),
path('redoImage',views.redoImage,name='redoImage'),
path('undoImage',views.undoImage,name='undoImage'),
path('scaleIt',views.scaleIt,name='scaleIt'),
path('cropImage',views.cropImage,name='cropImage'),
path('rotateImage',views.rotateImage,name='rotateImage'),
path('blurImage',views.blurImage,name='blurImage'),
path('sharpenImage',views.sharpenImage,name='sharpenImage'),
path('brightenImage',views.brightenImage,name='brightenImage'),
path('contrastImage',views.contrastImage,name='contrastImage'),
path('flipImage',views.flipImage,name='flipImage'),
path('watermarkImage',views.watermarkImage,name='watermarkImage'),
path('imposeImage',views.imposeImage,name='imposeImage'),

path('downloadZip',views.downloadZip,name='downloadZip'),
path('downloadPdf',views.downloadPdf,name='downloadPdf'),
path('invertImage',views.invertImage,name='invertImage'),
path('edgeDetection',views.edgeDetection,name='edgeDetection'),
path('erodeImage',views.erodeImage,name='erodeImage'),
path('dilateImage',views.dilateImage,name='dilateImage'),
path('drawLine',views.drawLine,name='drawLine'),
path('drawRectangle',views.drawRectangle,name='drawRectangle'),
path('drawCircle',views.drawCircle,name='drawCircle'),
path('drawText',views.drawText,name='drawText'),
path('drawPolygon',views.drawPolygon,name='drawPolygon'),
path('convertToJPG',views.convertToJPG,name='convertToJPG'),
path('convertToPNG',views.convertToPNG,name='convertToPNG'),
path('convertToBMP',views.convertToBMP,name='convertToBMP')

]
